/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_bgi_flexlab_metas_alignment_metasbowtie2_BowtieLJNI */

#ifndef _Included_org_bgi_flexlab_metas_alignment_metasbowtie2_BowtieLJNI
#define _Included_org_bgi_flexlab_metas_alignment_metasbowtie2_BowtieLJNI
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_bgi_flexlab_metas_alignment_metasbowtie2_BowtieLJNI
 * Method:    bowtie_jni
 * Signature: (I[Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_org_bgi_flexlab_metas_alignment_metasbowtie2_BowtieLJNI_bowtie_1jni
  (JNIEnv *, jobject, jint, jobjectArray);

#ifdef __cplusplus
}
#endif
#endif
